#!/usr/bin/env bash
set -eu

: "${CREW_PREFIX:=/usr/local}"

if [ -f "${CREW_PREFIX}/etc/sommelier.dpi" ]; then
  SOMMELIER_DPI="$(< ${CREW_PREFIX}/etc/sommelier.dpi)"
else
  SOMMELIER_DPI=96
fi

exec sommelier -X --glamor \
  --dpi=${SOMMELIER_DPI} \
  --x-auth=/home/chronos/.Xauthority \
  "${@}" --verbose
